@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.teamacronymcoders.base.util;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;